# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_destination', models.CharField(choices=[('EWR', 'EWR'), ('JFK', 'JFK'), ('LGA', 'LGA'), ('PHL', 'PHL'), ('PTON', 'Princeton')], max_length=100)),
                ('end_destination', models.CharField(choices=[('EWR', 'EWR'), ('JFK', 'JFK'), ('LGA', 'LGA'), ('PHL', 'PHL'), ('PTON', 'Princeton')], max_length=100)),
                ('date_time', models.DateTimeField(verbose_name='Date and time')),
                ('req_date_time', models.DateTimeField(auto_now_add=True)),
                ('seats', models.IntegerField(default=0)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('pools', models.ManyToManyField(to='app.Rides')),
            ],
        ),
        migrations.AddField(
            model_name='rides',
            name='usrs',
            field=models.ManyToManyField(to='app.Users'),
        ),
    ]
