# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170426_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
    ]
