# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_users_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='own_car',
        ),
        migrations.RemoveField(
            model_name='rides',
            name='owner',
        ),
    ]
