# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170428_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rides',
            options={'ordering': ['date_time']},
        ),
    ]
