# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170430_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rides',
            options={'ordering': ['date_time']},
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rides',
            name='end_destination',
            field=models.CharField(choices=[('EWR', 'EWR'), ('JFK', 'JFK'), ('LGA', 'LGA'), ('PHL', 'PHL'), ('PTON', 'Princeton'), ("Wegman's", "Wegman's"), ('Shop Rite', 'Shop Rite'), ("Trader Joe's", "Trader Joe's"), ('Target', 'Target'), ('Walmart', 'Walmart'), ('Costco', 'Costco'), ('Asian Foods Market Plainsboro', 'Asian Foods Market Plainsboro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rides',
            name='start_destination',
            field=models.CharField(choices=[('EWR', 'EWR'), ('JFK', 'JFK'), ('LGA', 'LGA'), ('PHL', 'PHL'), ('PTON', 'Princeton'), ("Wegman's", "Wegman's"), ('Shop Rite', 'Shop Rite'), ("Trader Joe's", "Trader Joe's"), ('Target', 'Target'), ('Walmart', 'Walmart'), ('Costco', 'Costco'), ('Asian Foods Market Plainsboro', 'Asian Foods Market Plainsboro')], max_length=100),
        ),
    ]
