# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170508_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rides',
            name='end_destination',
            field=models.CharField(choices=[('Newark (EWR)', 'Newark (EWR)'), ('John F. Kennedy (JFK)', 'John F. Kennedy (JFK)'), ('LaGuardia (LGA)', 'LaGuardia (LGA)'), ('Philadelphia (PHL)', 'Philadelphia (PHL)'), ('Princeton', 'Princeton'), ("Wegman's", "Wegman's"), ('Shop Rite', 'Shop Rite'), ("Trader Joe's", "Trader Joe's"), ('Target', 'Target'), ('Walmart', 'Walmart'), ('Costco', 'Costco'), ('Asian Food Markets (Plainsboro)', 'Asian Food Markets (Plainsboro)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rides',
            name='start_destination',
            field=models.CharField(choices=[('Newark (EWR)', 'Newark (EWR)'), ('John F. Kennedy (JFK)', 'John F. Kennedy (JFK)'), ('LaGuardia (LGA)', 'LaGuardia (LGA)'), ('Philadelphia (PHL)', 'Philadelphia (PHL)'), ('Princeton', 'Princeton'), ("Wegman's", "Wegman's"), ('Shop Rite', 'Shop Rite'), ("Trader Joe's", "Trader Joe's"), ('Target', 'Target'), ('Walmart', 'Walmart'), ('Costco', 'Costco'), ('Asian Food Markets (Plainsboro)', 'Asian Food Markets (Plainsboro)')], max_length=100),
        ),
    ]
